spring:
  datasource:
    url: jdbc:mysql://localhost:3306/revolver?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

debug: true

